"""initial_schema

Revision ID: 6aebac75a7a1
Revises: 66d18793a3d9
Create Date: 2026-04-04 15:01:48.977301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aebac75a7a1'
down_revision: Union[str, Sequence[str], None] = '66d18793a3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_history_account_date', table_name='balance_history')
    op.drop_index('ix_category_overrides_category_id', table_name='category_overrides')
    op.drop_index('ix_category_overrides_user_id', table_name='category_overrides')
    op.drop_index('idx_transactions_account_date_deleted', table_name='transactions')
    op.drop_index('idx_transactions_date_nature_deleted', table_name='transactions')
    op.drop_index('ix_transactions_account_deleted', table_name='transactions')
    op.drop_index('ix_transactions_user_date_deleted', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_user_date_deleted', 'transactions', ['user_id', 'date', 'deleted_at'], unique=False)
    op.create_index('ix_transactions_account_deleted', 'transactions', ['account_id', 'deleted_at'], unique=False)
    op.create_index('idx_transactions_date_nature_deleted', 'transactions', ['date', 'nature', 'deleted_at'], unique=False)
    op.create_index('idx_transactions_account_date_deleted', 'transactions', ['account_id', 'date', 'deleted_at'], unique=False)
    op.create_index('ix_category_overrides_user_id', 'category_overrides', ['user_id'], unique=False)
    op.create_index('ix_category_overrides_category_id', 'category_overrides', ['category_id'], unique=False)
    op.create_index('ix_balance_history_account_date', 'balance_history', ['account_id', 'date'], unique=False)
    # ### end Alembic commands ###
